CC = g++
CFLAGS = -Wall -g -std=c++11
SRC = src/quick_union_find.cpp
INCLUDES = -I./include
LIBS =
utilObjs = dynamic_connectivity.o

libdynamic_connectivity.a: $(utilObjs)
	ar rc $@ $(utilObjs)
	ranlib $@

dynamic_connectivity: dynamic_connectivity.o libdynamic_connectivity.a
	$(CC) $(CFLAGS) dynamic_connectivity.o 

dynamic_connectivity.o: $(SRC) 
	$(CC) $(CFLAGS) -c $< $(INCLUDES) $(LIBS) -o $@ 

clean:
	rm -rf *.o libdynamic_connectivity.a dynamic_connectivity

all: dynamic_connectivity 
.PHONY: all clean